config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    scope "/admin" do
      resources :applicants
      resources :invoices
          post 'send-invoice-notification-email/:id' => 'invoices#send_invoice_notification_email', as: :send_invoice_notification_email
      
      resources :vehicule_images
      resources :messages
      resources :quotes
      get 'my-quotes/' => 'quotes#my_quotes', as: :my_quotes
      post 'create-message-for-quote/:id' => 'quotes#create_message', as: :create_message_for_quote
      patch 'update_quote_assigned_user/:id' => 'quotes#update_quote_assigned_user', as: :update_quote_assigned_user
      resources :vehicules
      post 'change-user-points/:id' => 'customers#change_user_points', as: :change_user_points
      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
      

      
      resources :users
      get 'training-videos' => 'users#training_videos', as: :training_videos
      post 'send-reset-password/:id' => 'customers#send_reset_password', as: :send_reset_password

      resources :customers #, except: [:create, :edit, :update]
      
    end
  end

  devise_for :users
  #resources :customers, only: [:create, :edit, :update]
  mount_griddler
  mount Payola::Engine => '/payola', as: :payola

  # Customer Web Pages
  #patch '/customer/confirmation', :controller => 'customers/confirmations', :action => 'update', :conditions => { :method => :patch }, as: :update_customer_confirmation

  devise_for :customers, controllers: {
    registrations: 'customers/registrations',
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    confirmations: 'customers/confirmations'
  }


  devise_scope :customer do
    get "/change-password" => "customers/registrations#edit"
    post "/change-password" => "customers/registrations#update"
    patch '/customer/confirmation' => 'customers/confirmations#update', as: :update_customer_confirmation
  end
  get 'home' => 'web_page#home'
  get 'contact-us' => 'web_page#contact_us'
  get 'about-us' => 'web_page#about_us'
  get 'fleet' => 'web_page#fleet'
  get 'services' => 'web_page#services'
  get 'vehicule-details/:id' => 'web_page#vehicule_details', as: :vehicule_details
  get 'profile-settings' => 'web_page#profile_settings', as: :profile_settings
  get 'edit-profile-settings' => 'web_page#edit_profile_settings', as: :edit_profile_settings
  patch 'profile-settings' => 'web_page#update_profile_settings'
  get 'unpaid-customer-invoices' =>'web_page#show_unpaid_customer_invoices', as: :show_unpaid_customer_invoices
  get 'unpaid-customer-invoice/:id' =>'web_page#show_unpaid_customer_invoice', as: :show_unpaid_customer_invoice
  patch 'submit-accepted-invoice' =>'web_page#submit_accepted_invoice', as: :submit_accepted_invoice
  get 'quote-request' => 'web_page#quote_request'
  get 'quote-success' => 'web_page#quote_success_page', as: :quote_success_page
  post 'quote-request' => 'web_page#create_quote_request', as: :create_quote_request
  post 'contact-us' => 'web_page#create_contact_us_quote_request', as: :create_contact_us_quote_request
  get 'history' => 'web_page#history'
  get 'jobs' => 'web_page#jobs'
  get 'jobs/apply' => 'web_page#apply_job'
  post 'jobs/apply' => 'web_page#create_job_application', as: :create_job_application
  root 'web_page#home'
end

app/models/vehicule.rb
class Vehicule < ApplicationRecord
  has_many :vehicule_images, dependent: :destroy
  has_many :invoices
  has_many :quotes
  accepts_nested_attributes_for :vehicule_images, reject_if: proc { |attributes| attributes[:photo].blank? }, allow_destroy: true

  enum vehicule_types: [:shuttle, :limousine, :sedan, :bus]
  validates_presence_of :vehicule_type
  mount_uploader :display_image, ImageUploader

  def amenities
    items = []
    items << "tv" if tv
    items << "bathroom" if bathroom
    items << "dvd_player" if dvd_player
    items << "cd_player" if cd_player
    items << "am_fm_radio" if am_fm_radio
    items << "cooler" if cooler
    items << "nav_system" if nav_system
    items << "sound_system" if sound_system
    items << "wheelchair" if wheelchair
    items << "bluetooth" if bluetooth
    items << "leather" if leather
    items << "seats" unless seats.nil?

    items
  end
end

app/controllers/vehicules_controller.rb
class VehiculesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_vehicule, only: [:show, :edit, :update, :destroy]

  # GET /vehicules
  # GET /vehicules.json
  def index
    @vehicules = Vehicule.all
  end

  # GET /vehicules/1
  # GET /vehicules/1.json
  def show
    @vehicule_images = @vehicule.vehicule_images.all
  end

  # GET /vehicules/new
  def new
    @vehicule = Vehicule.new
    @vehicule.vehicule_images.build
    #@new_vehicule_image = @vehicule.vehicule_images.build
  end

  # GET /vehicules/1/edit
  def edit
    #@vehicule_images = @vehicule.vehicule_images
    @vehicule.vehicule_images.build
  end

  # POST /vehicules
  # POST /vehicules.json
  def create
    @vehicule = Vehicule.new(vehicule_params)
    if @vehicule.save
      redirect_to @vehicule, notice: 'Vehicule was successfully created.' 
    else
      render :new 
    end
  end

  # PATCH/PUT /vehicules/1
  # PATCH/PUT /vehicules/1.json
  def update
    respond_to do |format|
      if @vehicule.update(vehicule_params)
        format.html { redirect_to vehicules_path, notice: 'Vehicule was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicule }
      else
        format.html { render :edit }
        format.json { render json: @vehicule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicules/1
  # DELETE /vehicules/1.json
  def destroy
    @vehicule.destroy
    respond_to do |format|
      format.html { redirect_to vehicules_url, notice: 'Vehicule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicule
      @vehicule = Vehicule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicule_params
      params.require(:vehicule).permit(:name, :vehicule_type, :info, :display_image, :tv, :bathroom, 
          :dvd_player, :cd_player, :am_fm_radio, :cooler, :nav_system, :sound_system, :wheelchair, :bluetooth, 
          :leather, :seats, vehicule_images_attributes: [:id, :vehicule_id, :photo, :_destroy])
    end
end

app/helpers/vehicules_helper.rb
module VehiculesHelper
end

app/views/vehicules/_form.html.erb
<%= simple_form_for(@vehicule, :html => {:multipart => true}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="form-group">
      <%= f.input :name, input_html: {class: "form-control white_bg"}%>
    </div>
    <div class="form-group">
      <%= f.input :vehicule_type, :as => :select, :collection => Vehicule.vehicule_types.keys.to_a, input_html: {class: "form-control white_bg"} %>
    </div>
    <div class="form-group">
      <%= f.input :info, input_html: {class: "white_bg", :cols => 85, :rows => 8 } %>
    </div>
    <p>Main Image</p>
    <%= image_tag @vehicule.display_image, height: '150' %>
    <div class="form-group">
      <%= f.file_field :display_image %>
    </div>
    <div class="form-group">
      <%= f.input :seats, input_html: {class: "form-control white_bg"} %>
    </div>
    <div class="form-group">
      <%= f.input :tv %>
    </div>
    <div class="form-group">
      <%= f.input :bathroom %>
    </div>
    <div class="form-group">
      <%= f.input :dvd_player %>
    </div>
    <div class="form-group">
      <%= f.input :cd_player %>
    </div>
    <div class="form-group">
      <%= f.input :am_fm_radio %>
    </div>
    <div class="form-group">
      <%= f.input :cooler %>
    </div>
    <div class="form-group">
      <%= f.input :nav_system %>
    </div>
    <div class="form-group">
      <%= f.input :sound_system %>
    </div>
    <div class="form-group">
      <%= f.input :wheelchair %>
      </div>
    <div class="form-group">
      <%= f.input :bluetooth %>
    </div>
    <div class="form-group">
      <%= f.input :leather %>
    </div>

    <%= f.simple_fields_for :vehicule_images do |p| %>
     <div class="field">
      <%= image_tag p.object.photo, height: '150' %>
      <%= p.file_field :photo %>
      <%= p.check_box :_destroy %>
      <%= p.label :_destroy, "Remove Image" %>
     </div>
   <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Upadte Vehicle" %>
  </div>
<% end %>

app/views/vehicules/edit.html.erb
<div class="container">
  <h1>Editing Vehicle</h1>

  <%= render 'form', vehicule: @vehicule %>

  <%= link_to 'Show', @vehicule %> |
  <%= link_to 'Back', vehicules_path %>
</div>

app/views/vehicules/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Vehicles</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Image</th>
        <th>Type</th>
        <th>Seats</th>
        <th>Tv</th>
        <th>Bathroom</th>
        <th>Dvd player</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @vehicules.each do |vehicule| %>
        <tr>
          <td><%= vehicule.name %></td>
          <td><%= image_tag vehicule.display_image_url() if vehicule.display_image? %></td>
          <td><%= vehicule.vehicule_type %></td>
          <td><%= vehicule.seats %></td>
          <td><%= vehicule.tv %></td>
          <td><%= vehicule.bathroom %></td>
          <td><%= vehicule.dvd_player %></td>
          <td><%= link_to 'View', vehicule %>/<%= link_to 'Edit', edit_vehicule_path(vehicule) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br/>

  <%= link_to 'Add New Vehicle', new_vehicule_path, class: "btn" %>
</div>

app/views/vehicules/new.html.erb
<div class="container">
  <h1>New Vehicule</h1>

  <%= render 'form', vehicule: @vehicule %>

  <%= link_to 'Back', vehicules_path %>
</div>

app/views/vehicules/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @vehicule.name %>
  </p>
  <p>
  <%= image_tag @vehicule.display_image_url(), height: '200' if @vehicule.display_image? %>
  </p>
  <p>
    <strong>Type:</strong>
    <%= @vehicule.vehicule_type %>
  </p>

  <p>
    <strong>Info:</strong>
    <%= @vehicule.info %>
  </p>

  <p>
    <strong>Seats:</strong>
    <%= @vehicule.seats %>
  </p>

  <p>
    <strong>Tv:</strong>
    <%= @vehicule.tv %>
  </p>

  <p>
    <strong>Bathroom:</strong>
    <%= @vehicule.bathroom %>
  </p>

  <p>
    <strong>Dvd player:</strong>
    <%= @vehicule.dvd_player %>
  </p>

  <p>
    <strong>Cd player:</strong>
    <%= @vehicule.cd_player %>
  </p>

  <p>
    <strong>Am fm radio:</strong>
    <%= @vehicule.am_fm_radio %>
  </p>

  <p>
    <strong>Cooler:</strong>
    <%= @vehicule.cooler %>
  </p>

  <p>
    <strong>Nav system:</strong>
    <%= @vehicule.nav_system %>
  </p>

  <p>
    <strong>Sound system:</strong>
    <%= @vehicule.sound_system %>
  </p>

  <p>
    <strong>Wheelchair:</strong>
    <%= @vehicule.wheelchair %>
  </p>

  <p>
    <strong>Bluetooth:</strong>
    <%= @vehicule.bluetooth %>
  </p>

  <p>
    <strong>Leather:</strong>
    <%= @vehicule.leather %>
  </p>

  <div>
    <% @vehicule_images.each do |p| %>
      <%= image_tag p.photo.thumb %>
      <%# link_to "Edit Image", edit_vehicule_image_path(p) %>
    <% end %>
  </div>
  <div>
    <%= link_to 'Edit', edit_vehicule_path(@vehicule), class: "btn" %> |
    <%= link_to 'Back', vehicules_path, class: "btn" %>
  </div>
</div>