config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    scope "/admin" do
      resources :applicants
      resources :invoices
          post 'send-invoice-notification-email/:id' => 'invoices#send_invoice_notification_email', as: :send_invoice_notification_email
      
      resources :vehicule_images
      resources :messages
      resources :quotes
      get 'my-quotes/' => 'quotes#my_quotes', as: :my_quotes
      post 'create-message-for-quote/:id' => 'quotes#create_message', as: :create_message_for_quote
      patch 'update_quote_assigned_user/:id' => 'quotes#update_quote_assigned_user', as: :update_quote_assigned_user
      resources :vehicules
      post 'change-user-points/:id' => 'customers#change_user_points', as: :change_user_points
      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
      

      
      resources :users
      get 'training-videos' => 'users#training_videos', as: :training_videos
      post 'send-reset-password/:id' => 'customers#send_reset_password', as: :send_reset_password

      resources :customers #, except: [:create, :edit, :update]
      
    end
  end

  devise_for :users
  #resources :customers, only: [:create, :edit, :update]
  mount_griddler
  mount Payola::Engine => '/payola', as: :payola

  # Customer Web Pages
  #patch '/customer/confirmation', :controller => 'customers/confirmations', :action => 'update', :conditions => { :method => :patch }, as: :update_customer_confirmation

  devise_for :customers, controllers: {
    registrations: 'customers/registrations',
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    confirmations: 'customers/confirmations'
  }


  devise_scope :customer do
    get "/change-password" => "customers/registrations#edit"
    post "/change-password" => "customers/registrations#update"
    patch '/customer/confirmation' => 'customers/confirmations#update', as: :update_customer_confirmation
  end
  get 'home' => 'web_page#home'
  get 'contact-us' => 'web_page#contact_us'
  get 'about-us' => 'web_page#about_us'
  get 'fleet' => 'web_page#fleet'
  get 'services' => 'web_page#services'
  get 'vehicule-details/:id' => 'web_page#vehicule_details', as: :vehicule_details
  get 'profile-settings' => 'web_page#profile_settings', as: :profile_settings
  get 'edit-profile-settings' => 'web_page#edit_profile_settings', as: :edit_profile_settings
  patch 'profile-settings' => 'web_page#update_profile_settings'
  get 'unpaid-customer-invoices' =>'web_page#show_unpaid_customer_invoices', as: :show_unpaid_customer_invoices
  get 'unpaid-customer-invoice/:id' =>'web_page#show_unpaid_customer_invoice', as: :show_unpaid_customer_invoice
  patch 'submit-accepted-invoice' =>'web_page#submit_accepted_invoice', as: :submit_accepted_invoice
  get 'quote-request' => 'web_page#quote_request'
  get 'quote-success' => 'web_page#quote_success_page', as: :quote_success_page
  post 'quote-request' => 'web_page#create_quote_request', as: :create_quote_request
  post 'contact-us' => 'web_page#create_contact_us_quote_request', as: :create_contact_us_quote_request
  get 'history' => 'web_page#history'
  get 'jobs' => 'web_page#jobs'
  get 'jobs/apply' => 'web_page#apply_job'
  post 'jobs/apply' => 'web_page#create_job_application', as: :create_job_application
  root 'web_page#home'
end

app/models/quote.rb
class Quote < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :user
  belongs_to :customer
  has_many :invoices
  belongs_to :vehicule, class_name: "Vehicule", foreign_key: "vehicule_type"
  
  validates_presence_of :email
  validates_presence_of :first_name, :unless => :no_quote_type
  validates_presence_of :last_name, :unless => :no_quote_type

  after_create :send_quote_confirmation

  scope :by_user, ->(id) { where("user_id = ?", id)  }

  def send_quote_confirmation
    #don't send quote received confirmation if type is nil (i.e. we received an email)
    unless self.type.nil?
      QuoteMailer.quote_confirmation_email(self).deliver 
    end
  end

  def send_quote_assignment_notice
    QuoteMailer.quote_assignment_email(self).deliver 
  end

  def email_token
    id.to_s + '-request'
  end

  def quote_fields
    [:first_name, :last_name, :email, :phone_number, :organization, :extension, :additional_notes, :departure_date, :airport, 
      :departure_time, :departure_address, :flight_num, :pay_method, :num_of_passengers, :total_num_of_days, :return_date, :return_time, 
      :destination_address, :itinirary]
  end

  def full_name
    (first_name || '') + ' ' + ( last_name || '')
  end

  def no_quote_type
    return type.nil?
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_quote, only: [:show, :edit, :update, :destroy, :update_quote_assigned_user]

  # GET /quotes
  # GET /quotes.json
  def index
    @q = Quote.ransack(params[:q])
    @quotes = @q.result(distinct: true).order('updated_at desc').paginate(:page => params[:page], per_page: 12)
    @users_select = User.where(active: true).map {|u| [u.full_name, u.id]}
  end

  def my_quotes
    @q = Quote.by_user(current_user.id).ransack(params[:q])
    @quotes = @q.result(distinct: true).order('updated_at desc').paginate(:page => params[:page], per_page: 12)
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    @messages = @quote.messages
    @message = @quote.messages.build
    @users_select = User.where(active: true).map {|u| [u.full_name, u.id]}
    #@message.user_id = current_user.try(:id)
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_message
    @message = Message.new(message_params)
    @message.raw_body = Sanitize.fragment(@message.body, Sanitize::Config::RELAXED)
    @message.user_id = current_user.try(:id)
    if @message.save
      redirect_to quote_path(@message.quote.id), notice: 'Message was successfully created.'
    else
      render "quotes/new" 
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_quote_assigned_user
    respond_to do |format|
      if not(quote_params[:user_id].blank?) and @quote.update(quote_params)
        format.html { redirect_to quotes_path, notice: 'User was successfully assigned.' }
        @quote.send_quote_assignment_notice
      else
        flash[:error] = "Sorry, unable to assign user."
        format.html { redirect_to quotes_path }
        #format.html { render :edit }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    def message_params
      params.require(:message).permit(:body, :quote_id, :user_id, :customer_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      if params[:airport_pickup_quote]
        result = params.require(:airport_pickup_quote)
      elsif params[:airport_dropoff_quote]
        result = params.require(:airport_dropoff_quote)
      elsif params[:out_of_town_quote]
        result = params.require(:out_of_town_quote)
      elsif params[:contract_quote]
        result = params.require(:contract_quote)  
      elsif params[:special_event_quote]
        result = params.require(:special_event_quote)
      elsif params[:contact_us_quote]
        result = params.require(:contact_us_quote)  
      else
        result = params.require(:quote)
      end
      result.permit(:first_name, :last_name, :email, :phone_number, :service_type, :type, :customer_id, 
            :organization, :address, :extension, :departure_date, :departure_time, :departure_address, 
            :destination_address, :vehicule_type, :itinirary, :additional_notes, :total_num_of_days, :return_date, 
            :return_time, :num_of_passengers, :num_of_bags, :airport, :flight_num, :pay_method, :flight_departure_time, :user_id)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end
module BootstrapPaginationHelper
    class LinkRenderer < WillPaginate::ActionView::LinkRenderer
        protected
      def page_number(page)
        unless page == current_page
          link(page, page, :rel => rel_value(page))
        else
          link(page, "#", :class => 'active')
        end
      end
      def gap
        text = @template.will_paginate_translate(:page_gap) { '&hellip;' }
        %(<li class="disabled"><a>#{text}</a></li>)
      end
      def next_page
        num = @collection.current_page < @collection.total_pages && @collection.current_page + 1
        previous_or_next_page(num, @options[:next_label], 'next')
      end
      def previous_or_next_page(page, text, classname)
        if page
          link(text, page, :class => classname)
        else
          link(text, "#", :class => classname + ' disabled')
        end
      end
      def html_container(html)
        tag(:div, tag(:ul, html), container_attributes)
      end
    private
        def link(text, target, attributes = {})
        if target.is_a? Fixnum
          attributes[:rel] = rel_value(target)
          target = url(target)
        end
                unless target == "#"
                    attributes[:href] = target
                end
        classname = attributes[:class]
        attributes.delete(:classname)
        tag(:li, tag(:a, text, attributes), :class => classname)
        end
    end
end

app/views/quotes/_form.html.erb
<%= simple_form_for(@quote) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
    <%= f.input :phone_number %>
    <%= f.input :service_type %>
    <%= f.input :vehicule_type %>
    <%= f.input :num_of_passengers %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h2>Quotes</h2>
  <div>
    <p>
    <%= search_form_for @q do |f| %>
      <div style="width:30%;float:left;padding-right:10px;padding-bottom:10px">
        <%= f.label :email_cont%>
        <%= f.search_field :email_cont, class: "form-control white_bg" %>
      </div>
      <div style="width:30%;float:left;padding-right:10px;padding-bottom:10px">
        <%= f.label :first_name_cont%>
        <%= f.search_field :first_name_cont, class: "form-control white_bg" %>
      </div>
      <div style="width:30%;float:left;padding-bottom:10px">
        <%= f.label :last_name_cont%>
        <%= f.search_field :last_name_cont, class: "form-control white_bg" %>
      </div>
      <div>
        <%= f.submit class: "btn" %>
      </div>
    <% end %>
    </p>
  </div>
  <div class="table-paginate"><%= will_paginate(@quotes, :renderer => 'BootstrapPaginationHelper::LinkRenderer' ) %></div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Date Rec</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Phone number</th>
        <th>Type</th>
        <th>Invoice</th>
        <th>Assign</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @quotes.each do |quote| %>
        <tr>
          <td><%= quote.created_at.strftime("%m/%d/%Y %I:%M %p") %></td>
          <td><%= quote.first_name %></td>
          <td><%= quote.last_name %></td>
          <td><%= quote.email %></td>
          <td><%= quote.phone_number %></td>
          <td><%= quote.type %></td>
          <td><ul class="quote-invoice-status"><% if quote.invoices.count 
                    quote.invoices.each do |inv| %>
                      <li><%= link_to inv.status, inv %></li>
                    <% end
                  end %>
          </ul></td>
          <td>
            <% if quote.user.nil? %>
              <%= simple_form_for quote, url: update_quote_assigned_user_path(quote), method: :patch do |f| %>
                <div class="form-group select">
                  <%= f.input :user_id , collection: @users_select, input_html: { class: "form-control white_bg" }, label: false %>
                </div>
                <div class="form-group">
                  <%= f.button :submit, value: "Assign", class: "btn btn-success" %>
                </div>
              <% end %>
            <% else %>
              <%= quote.user.full_name %>
            <% end %>
          </td> 
          <td><%= link_to 'Show', quote_path(quote) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/quotes/my_quotes.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h2>Quotes</h2>
  <div>
    <p>
    <%= search_form_for @q do |f| %>
      <div style="width:30%;float:left;padding-right:10px;padding-bottom:10px">
        <%= f.label :email_cont%>
        <%= f.search_field :email_cont, class: "form-control white_bg" %>
      </div>
      <div style="width:30%;float:left;padding-right:10px;padding-bottom:10px">
        <%= f.label :first_name_cont%>
        <%= f.search_field :first_name_cont, class: "form-control white_bg" %>
      </div>
      <div style="width:30%;float:left;padding-bottom:10px">
        <%= f.label :last_name_cont%>
        <%= f.search_field :last_name_cont, class: "form-control white_bg" %>
      </div>
      <div>
        <%= f.submit class: "btn" %>
      </div>
    <% end %>
    </p>
  </div>
  <div class="table-paginate"><%= will_paginate(@quotes, :renderer => 'BootstrapPaginationHelper::LinkRenderer' ) %></div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Phone number</th>
        <th>Type</th>
        <th>Invoice</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @quotes.each do |quote| %>
        <tr>
          <td><%= quote.first_name %></td>
          <td><%= quote.last_name %></td>
          <td><%= quote.email %></td>
          <td><%= quote.phone_number %></td>
          <td><%= quote.type %></td>
          <td><ul class="quote-invoice-status"><% if quote.invoices.count 
                    quote.invoices.each do |inv| %>
                      <li><%= link_to inv.status, inv %></li>
                    <% end
                  end %>
          </ul></td>
          <td><%= link_to 'Show', quote_path(quote) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>

  <div class="col-md-4 col-sm-8">
    <div class="profile_wrap">
      <dl class="dl-horizontal">
        <dt><strong>first name:</strong></dt>
        <dd><%= @quote.first_name %></dd>
        <dt><strong>last name:</strong></dt>
        <dd><%= @quote.last_name %></dd>
        <dt><strong>email:</strong></dt>
        <dd><%= @quote.email %></dd>
        <dt><strong>phone number:</strong></dt>
        <dd><%= @quote.phone_number %></dd>
        <dt><strong>organization:</strong></dt>
        <dd><%= @quote.organization %></dd>
        <dt><strong>type:</strong></dt>
        <dd><%= @quote.type %></dd>
         <dt><strong>airport:</strong></dt>
        <dd><%= @quote.airport %></dd>
        <dt><strong>flight num:</strong></dt>
        <dd><%= @quote.flight_num %></dd>
        <dt><strong>flight departure time:</strong></dt>
        <dd><%= @quote.departure_time.strftime("%I:%M %p") unless @quote.departure_time.nil? %></dd>

      </dl>
    </div>
  </div>

  <div class="col-md-4 col-sm-8">
    <div class="profile_wrap">
      <dl class="dl-horizontal">
        <dt><strong>customer:</strong></dt>
        <dd><%= @quote.customer_id %></dd>
        <dt><strong>vehicule type:</strong></dt>
        <dd><%= @quote.vehicule_type %></dd>
        <dt><strong>Number of passengers:</strong></dt>
        <dd><%= @quote.num_of_passengers %></dd>
        <dt><strong>Number of bags:</strong></dt>
        <dd><%= @quote.num_of_bags %></dd>
        <dt><strong>address:</strong></dt>
        <dd><%= @quote.address %></dd>
        <dt><strong>extension:</strong></dt>
        <dd><%= @quote.extension %></dd>
        <dt><strong>departure_date:</strong></dt>
        <dd><%= @quote.departure_date.strftime("%b %d, %Y") unless @quote.departure_date.nil?%></dd>
        <dt><strong>departure_address:</strong></dt>
        <dd><%= @quote.departure_address %></dd>
        <dt><strong>destination_address:</strong></dt>
        <dd><%= @quote.destination_address %></dd>
        
      </dl>
    </div>
  </div>
  <div class="col-md-4 col-sm-8">
    <div class="profile_wrap">
      <dl class="dl-horizontal">
        <dt><strong>total_num_of_days:</strong></dt>
        <dd><%= @quote.total_num_of_days %></dd>
        <dt><strong>Return date:</strong></dt>
        <dd><%= @quote.return_date.strftime("%b %d, %Y") unless @quote.return_date.nil? %></dd>
        <dt><strong>return time:</strong></dt>
        <dd><%= @quote.return_time.strftime("%I:%M %p") unless @quote.return_time.nil? %></dd>
        <dt><strong>Payment method:</strong></dt>
        <dd><%= @quote.pay_method %></dd>
      </dl>
    </div>
  </div>

  <div class="col-md-12">
    <div class="profile_wrap">
      <dl class="dl-horizontal">
        <dt><strong>itinirary:</strong></dt>
        <dd><%= @quote.itinirary %></dd>
      </dl>
    </div>
  </div>
  <div class="col-md-12">
    <div class="profile_wrap">
      <dl class="dl-horizontal">
        <dt><strong>Additional Notes:</strong></dt>
        <dd><%= @quote.additional_notes %></dd>
      </dl>
    </div>
  </div>

  <hr style="clear:both"/>
  <div class="col-md-9" style="padding:10px;background-color:#3deb73;">
    <% if @quote.invoices.count > 0 %> 
      <h5>Related Invoice(s)</h5>
      <ul>
        <% @quote.invoices.each do |invoice| %>
          <li style="font-size:1.5em"><%= link_to "Related Invoice", invoice_path(invoice.id)  %></li>
        <% end %>
      </ul>
    <% else %>
      <%= link_to "Convert to Invoice", new_invoice_path(quote_id: @quote.id) , class: "btn" %>
    <% end %>
  </div>

  <div class="col-md-3">
    <%= simple_form_for @quote, url: update_quote_assigned_user_path(@quote), method: :patch do |f| %>
      <div class="form-group select">
        <%= f.input :user_id , collection: @users_select, input_html: { class: "form-control white_bg" }, label: false %>
      </div>
      <div class="form-group">
        <%= f.button :submit, value: "Re-Assign", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>

  <div class="panel-body">
    <ul class="chat">
      <% @messages.each do |message| %>
        <% if message.owner == "user" %>
          <li class="left clearfix"><span class="chat-img pull-left">
              <img src="http://placehold.it/50/55C1E7/fff&text=REP" alt="User Avatar" class="img-circle" />
          </span>
              <div class="chat-body clearfix">
                  <div class="header">
                      <strong class="primary-font"><%= message.user.full_name %></strong> <small class="pull-right text-muted">
                          <span class="glyphicon glyphicon-time"></span><%= message.created_at.strftime("%b-%d-%Y at %I:%M %p") %></small>
                  </div>
                  <%= simple_format message.body %>
              </div>
          </li>
        <% elsif message.owner == "customer" %>
          <li class="right clearfix"><span class="chat-img pull-right">
              <img src="http://placehold.it/50/FA6F57/fff&text=CUST" alt="User Avatar" class="img-circle" />
          </span>
              <div class="chat-body clearfix">
                  <div class="header">
                      <small class=" text-muted"><span class="glyphicon glyphicon-time"></span><%= message.created_at.strftime("%b-%d-%Y at %I:%M %p") %></small>
                      <strong class="pull-right primary-font"><%= message.quote.full_name %></strong>
                  </div>
                  <%= simple_format message.body %>
              </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div> 

  <div class="row" style="padding-bottom:20px">
    <div class="col-md-12">
      <%= simple_form_for(@message, url: create_message_for_quote_path(@quote), method: :post) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :quote_id, as: :hidden %>
          <%= f.input :user_id, as: :hidden %>
          <div class="row">
            <div class="form-group col-md-8">
              <%= f.input :body, autofocus: true, as: :text, input_html: {class: " white_bg", :cols => 105, :rows => 8 } %>
            </div>
          </div>
        </div>

        <div class="form-actions">
          <%= f.button :submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>