config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    scope "/admin" do
      resources :applicants
      resources :invoices
          post 'send-invoice-notification-email/:id' => 'invoices#send_invoice_notification_email', as: :send_invoice_notification_email
      
      resources :vehicule_images
      resources :messages
      resources :quotes
      get 'my-quotes/' => 'quotes#my_quotes', as: :my_quotes
      post 'create-message-for-quote/:id' => 'quotes#create_message', as: :create_message_for_quote
      patch 'update_quote_assigned_user/:id' => 'quotes#update_quote_assigned_user', as: :update_quote_assigned_user
      resources :vehicules
      post 'change-user-points/:id' => 'customers#change_user_points', as: :change_user_points
      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
      

      
      resources :users
      get 'training-videos' => 'users#training_videos', as: :training_videos
      post 'send-reset-password/:id' => 'customers#send_reset_password', as: :send_reset_password

      resources :customers #, except: [:create, :edit, :update]
      
    end
  end

  devise_for :users
  #resources :customers, only: [:create, :edit, :update]
  mount_griddler
  mount Payola::Engine => '/payola', as: :payola

  # Customer Web Pages
  #patch '/customer/confirmation', :controller => 'customers/confirmations', :action => 'update', :conditions => { :method => :patch }, as: :update_customer_confirmation

  devise_for :customers, controllers: {
    registrations: 'customers/registrations',
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    confirmations: 'customers/confirmations'
  }


  devise_scope :customer do
    get "/change-password" => "customers/registrations#edit"
    post "/change-password" => "customers/registrations#update"
    patch '/customer/confirmation' => 'customers/confirmations#update', as: :update_customer_confirmation
  end
  get 'home' => 'web_page#home'
  get 'contact-us' => 'web_page#contact_us'
  get 'about-us' => 'web_page#about_us'
  get 'fleet' => 'web_page#fleet'
  get 'services' => 'web_page#services'
  get 'vehicule-details/:id' => 'web_page#vehicule_details', as: :vehicule_details
  get 'profile-settings' => 'web_page#profile_settings', as: :profile_settings
  get 'edit-profile-settings' => 'web_page#edit_profile_settings', as: :edit_profile_settings
  patch 'profile-settings' => 'web_page#update_profile_settings'
  get 'unpaid-customer-invoices' =>'web_page#show_unpaid_customer_invoices', as: :show_unpaid_customer_invoices
  get 'unpaid-customer-invoice/:id' =>'web_page#show_unpaid_customer_invoice', as: :show_unpaid_customer_invoice
  patch 'submit-accepted-invoice' =>'web_page#submit_accepted_invoice', as: :submit_accepted_invoice
  get 'quote-request' => 'web_page#quote_request'
  get 'quote-success' => 'web_page#quote_success_page', as: :quote_success_page
  post 'quote-request' => 'web_page#create_quote_request', as: :create_quote_request
  post 'contact-us' => 'web_page#create_contact_us_quote_request', as: :create_contact_us_quote_request
  get 'history' => 'web_page#history'
  get 'jobs' => 'web_page#jobs'
  get 'jobs/apply' => 'web_page#apply_job'
  post 'jobs/apply' => 'web_page#create_job_application', as: :create_job_application
  root 'web_page#home'
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  include Payola::Sellable
  belongs_to :quote
  belongs_to :customer
  belongs_to :sales_rep, class_name: "User", foreign_key: "user_id"
  belongs_to :vehicule

  validates_presence_of :quote
  validates_presence_of :customer
  validates_presence_of :sales_rep
  
  after_create :update_payola_info
  before_save :update_payola_price_info

  def update_payola_info
    self.name = "Invoice ##{self.id}" 
    self.permalink =  "invoice-#{self.id}"
    self.price = 100 * (self.rate || 0)
    self.save
  end

  # Turn price from dollars to cents b/c stripe assumes cents
  def update_payola_price_info
    self.price = 100 * (self.rate || 0)
  end

  def send_invoice_notification
    QuoteMailer.invoice_notification_email(self).deliver
  end

  def status
    return "paid" if payed
    return "accepted" if accepted
    return  "pending"
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy, :send_invoice_notification_email]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    @invoice.quote_id = params[:quote_id]
    random_num = rand(1..10000)
    @invoice.name = "placeholder-#{random_num}"
    @invoice.permalink = "placeholder-#{random_num}"
    @invoice.price = 0
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)
    authorize @invoice
    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def send_invoice_notification_email
    @invoice.send_invoice_notification
    @invoice.update_attributes(emailsent: true)
    redirect_to @invoice, notice: 'Invoice email notification was sent.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:price, :permalink, :name, :quote_id, :customer_id, :date_reserved, :date_needed, :user_id, :first_name,
        :last_name, :phone, :email, :itinerary, :handicap_accessible, :public_availability, :method_of_pay, :rate, :sales_tax, :deposit, :amount_due,
        :additional_charges, :total_collected, :time_reserved, :vehicule_id, :accepted, :unit)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<div class="invoice_form">
  <%= simple_form_for(@invoice) do |f| %>
    <%= f.error_notification %>

    <%= f.input :price, as: :hidden %>
    <%= f.input :permalink, as: :hidden %>
    <%= f.input :name, as: :hidden %>
    
    <div class="row">
      <%= f.input :quote_id, as: :hidden %>
      <div class="form-group col-md-6">
        <%= f.association :customer, collection: Customer.where(active: true).map{|c| ["#{c.full_name} - (#{c.email})", c.id]}, input_html: { class: 'chosen-select' } %>
      </div>
      <div class="form-group col-md-6">
        <%= f.association :sales_rep, collection: User.where(active: true).map{|c| ["#{c.full_name} - (#{c.email})", c.id]}, input_html: { class: 'chosen-select form-control white_bg' } %>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-md-6">
        <%= f.association :vehicule, collection: Vehicule.all.map{|c| [c.name, c.id]}, input_html: { class: 'chosen-select form-control white_bg' } %>
      </div>
      <div class="form-group col-md-6">
        <%= f.input :unit, input_html: {class: "form-control white_bg"} %>
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-4">
        <%= f.input :date_needed, as: :string, input_html: {class: "form-control white_bg datepicker"} %>
      </div>
      <div class="form-group col-md-4">
        <%= f.input :date_reserved, as: :string,  input_html: {class: "form-control white_bg datepicker"} %>
      </div>
      <div class="form-group col-md-4">
        <%= f.input :time_reserved, as: :string, input_html: {class: "form-control white_bg", :data =>{:provide => "timepicker"}} %>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-md-3">
        <%= f.input :first_name, input_html: {class: "form-control white_bg"} %>
      </div>
      <div class="form-group col-md-3">
        <%= f.input :last_name, input_html: {class: "form-control white_bg"} %>
      </div>
      <div class="form-group col-md-3">
        <%= f.input :phone, input_html: {class: "form-control white_bg"} %>
      </div>
      <div class="form-group col-md-3">
        <%= f.input :email, input_html: {class: "form-control white_bg"} %>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-md-10">
        <%= f.input :itinerary,  input_html: { class: "form-control white_bg", :cols => 65, :rows => 8} %>
      </div>
      <div class="form-group col-md-2">
        <%= f.input :handicap_accessible, input_html: {class: "form-control white_bg"} %>
        <br /><br /><br />
        <%= f.input :public_availability, input_html: {class: "form-control white_bg"} %>
      </div>
    </div>

    <div class="row">
      
      <div class="form-group col-md-3">
        <%= f.input :method_of_pay,  input_html: {class: "form-control white_bg"} %>
      </div>
      <div class="form-group col-md-3">
        <%= f.input :rate, input_html: {class: "form-control white_bg"} %>
      </div>
      <div class="form-group col-md-3">
        <%= f.input :sales_tax, input_html: {class: "form-control white_bg"} %>
      </div>
      <div class="form-group col-md-3">
        <%= f.input :deposit,  input_html: {class: "form-control white_bg"} %>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-md-3">
        <%= f.input :amount_due, input_html: {class: "form-control white_bg"} %>
      </div>
      <div class="form-group col-md-3">
        <%= f.input :additional_charges, input_html: {class: "form-control white_bg"} %>
      </div>
      <div class="form-group col-md-3">
        <%= f.input :total_collected, input_html: {class: "form-control white_bg"} %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/invoices/edit.html.erb
<div class="container">
  <h1>Editing Invoice</h1>

  <%= render 'form', invoice: @invoice %>

  <%= link_to 'Show', @invoice %> |
  <%= link_to 'Back', invoices_path %>
</div>

app/views/invoices/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Invoices</h1>

  <table>
    <thead>
      <tr>
        <th>Rate</th>
        <th>Vehicule</th>
        <th>Rep</th>
        <th>Quote</th>
        <th>Customer</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @invoices.each do |invoice| %>
        <tr>
          <td><%= invoice.rate %></td>
          <td><%= invoice.vehicule.try(:name) %> - <%= invoice.unit %></td>
          <td><%= invoice.sales_rep.try(:full_name) %></td>
          <td><%= "Quote# #{invoice.quote.id} for (#{invoice.quote.email})" %></td>
          <td><%= "#{invoice.customer.try(:full_name)} - (#{invoice.customer.try(:email)})" %></td>
          <td><%= link_to 'Show', invoice %></td>
          <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
          <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Invoice', new_invoice_path, class: "btn" %>
</div>

app/views/invoices/new.html.erb
<div class="container">
  <h1>New Invoice</h1>

  <%= render 'form', invoice: @invoice %>

  <%= link_to 'Back', invoices_path, class: "btn" %>
</div>

app/views/invoices/show.html.erb
<div class="container">
  <h2>Invoice</h2>
  <table>
    <tbody>
      <tr>
        <td style="width:50%"><strong>Date Reserved:</strong> <%= @invoice.date_reserved %></td>
        <td><strong>Sales Rep:</strong> <%= @invoice.sales_rep.try(:full_name) %></td>
      </tr>
      <tr>
        <td><strong>Date Needed:</strong> <%= @invoice.date_needed %></td>        
        <td><strong>Name:</strong> <%= @invoice.customer.try(:full_name) %></td>
      </tr>
      <tr>
        <td><strong>Phone:</strong> <%= @invoice.phone %></td>
        <td><strong>Email:</strong> <%= @invoice.email %></td>
      </tr>
      <tr>
        <td><strong>Vehicle:</strong> <%= @invoice.vehicule.try(:name) %> - <%= @invoice.unit %></td>
        <td><strong>Time:</strong> <%= @invoice.time_reserved %></td>
      </tr>
      <tr>
        <td colspan="2"><strong>Itinerary:</strong>  <%= @invoice.itinerary %></td>
      </tr>
      <tr>
        <td><strong>Handicap Accessible Required:</strong> <%= @invoice.handicap_accessible %></td>
        <td><strong>Is this event for which you are requesting our services available to the public?:</strong> <%= @invoice.public_availability %></td>
      </tr>
      <tr>
        <td><strong>Method of Pay:</strong><%= @invoice.method_of_pay %></td>
        <td><strong>Rate:</strong> <%= number_to_currency(@invoice.rate, precision: 2) %></td>
      </tr>
      <tr>
        <td><strong>Sales Tax:</strong> <%= number_to_currency(@invoice.sales_tax, precision: 2) %></td>
        <td><strong>Deposit:</strong> <%= number_to_currency(@invoice.deposit, precision: 2) %></td>
      </tr>
      <tr>
        <td><strong>Amount due:</strong> <%= number_to_currency(@invoice.amount_due, precision: 2) %></td>
        <td><strong>Additional Charges:</strong> <%= number_to_currency(@invoice.additional_charges, precision: 2) %></td>
      </tr>
      <tr>
        <td><strong>Total Amount Collected:</strong> <%= number_to_currency(@invoice.total_collected, precision: 2) %></td>
        <td><strong>Accepted:</strong> <%= @invoice.accepted %></td>
      </tr>
    </tbody>
  </table>  
  <div class ="invoice_terms_cond">
      <p>TERMS AND CONDITIONS</p>
      <u><p><strong>
        THE CLIENT ASSUMES FULL FINANCIAL RESPONSIBILITY AND AUTHORIZES CREDIT CARD CHARGES FOR: ANY DAMAGESTO THE VEHICLE AND/OR PROPERTY CAUSED BY THE CLIENT AND/OR HIS/HER GUESTS, WHETHER CAUSED BY ACCIDENT,NEGLECT, OR INTENT, OVERTIME FEES, AND ANY OTHER COSTS DUE AND NOT COLLECTED AT THE END OF THE CHARTER.NOT RESPONSIBLE FOR ANY LOST, STOLEN OR MISPLACED ITEMS. UNUSED TIME IS NOT REFUNDED. ADDITIONAL FEESASSOCIATED WITH TRIP SUCH AS INSURANCE FEE FOR CERTIFICATE, ADDITIONAL INSURED OR WAIVER OF SUBROGATION ETC.WILL AUTOMATICALLY BE CHARGED.</strong>
      </p>
      <p><strong>
        PER D.O.T. REGULATIONS, AFTER 10 HOURS OF DRIVING OR 14 HOURS OF SERVICE (WHICHEVERCOMES FIRST), THE DRIVER MUST TAKE 10 HOURS OFF DUTY BEFORE RETURNING TO WORK.</strong>
      </p>
      <p><strong>
        THE DRIVER MAY, AT HIS OR HER DISCRETION, TERMINATE THE CHARTER WITHOUT REFUND SHOULD HE/SHE DEEM THECLIENT AND/OR ANYONE IN THE CLIENT’S PARTY, UNRULY, INTERFERING WITH SAFE OPERATION OF THE VEHICLE, ORENGAGING IN ANY ILLEGAL ACTIVITY. SMOKING IN THE VEHICLES IS PROHIBITED. NO ALCOHOLIC BEVERAGES AREPERMITTED IF ANYONE UNDER THE AGE OF 21 IS BEING TRANSPORTED.</strong>
      </p>
      <p style="color:red"><strong>
        A 20% DEPOSIT IS REQUIRED TO RESERVE ANY VEHICLE. ALL MONEY PAID TOWARDS THE TRIP ISNON-REFUNDABLE. BALANCE TO BE PAID PRIOR TO SERVICE DATE.</strong>
      </p>
      <p><strong>
        **ADDITIONAL CHARGES: SICK/VOMIT FEE: $100.00, PER OCCURRENCE. EXCESSIVE CLEANING FEE: $100.00, DAMAGES: PERESTIMATE, OVERTIME: HOURLY RATE** </strong>
      </p>
      <p><strong>
        URBAN EXPRESS DOES NOT PROVIDE CAR SEATS. SOME VEHICLES BY DESIGN DO NOT REQUIRE SEAT BELTS. BY SIGNING THISCONTRACT, YOU AGREE TO HOLD URBAN EXPRESS HARMLESS FROM ANY ISSUE THAT MAY ARISE DUE TO THESE FACT.
      </p></strong>
      <p><strong>
        URBAN EXPRESS CHARTER CANNOT BE HELD LIABLE FOR MISSING, LOST, OR STOLEN ITEMS. URBAN EXPRESS CHARTERCANNOT BE HELD RESPONSIBLE FOR DELAYS OR INCONVENIENCES DUE TO TRAFFIC, UNKNOWN/UNSEEN MECHANICALFAILURES AND/OR SITUATIONS DEEMED AN ACT OF GOD. ANY BY SIGNING BELOW THE CLIENT AGREES TO ALL OF THE ABOVETERMS AND CONDITIONS.</strong>
      </p></u>
    </div>
  <% unless @invoice.emailsent %>
    <%= link_to 'Send Invoice Email Notice', send_invoice_notification_email_path(@invoice), class: "btn", method: :post %>
  <% end %>
  <%= link_to "Print", '#', class: "btn btn-primary", 
            onclick: 'window.print();return false;' %>
  <%= link_to 'Edit', edit_invoice_path(@invoice), class: "btn" %> |
  <%= link_to 'Back', invoices_path, class: "btn" %>
</div>