config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    scope "/admin" do
      resources :applicants
      resources :invoices
          post 'send-invoice-notification-email/:id' => 'invoices#send_invoice_notification_email', as: :send_invoice_notification_email
      
      resources :vehicule_images
      resources :messages
      resources :quotes
      get 'my-quotes/' => 'quotes#my_quotes', as: :my_quotes
      post 'create-message-for-quote/:id' => 'quotes#create_message', as: :create_message_for_quote
      patch 'update_quote_assigned_user/:id' => 'quotes#update_quote_assigned_user', as: :update_quote_assigned_user
      resources :vehicules
      post 'change-user-points/:id' => 'customers#change_user_points', as: :change_user_points
      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
      

      
      resources :users
      get 'training-videos' => 'users#training_videos', as: :training_videos
      post 'send-reset-password/:id' => 'customers#send_reset_password', as: :send_reset_password

      resources :customers #, except: [:create, :edit, :update]
      
    end
  end

  devise_for :users
  #resources :customers, only: [:create, :edit, :update]
  mount_griddler
  mount Payola::Engine => '/payola', as: :payola

  # Customer Web Pages
  #patch '/customer/confirmation', :controller => 'customers/confirmations', :action => 'update', :conditions => { :method => :patch }, as: :update_customer_confirmation

  devise_for :customers, controllers: {
    registrations: 'customers/registrations',
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    confirmations: 'customers/confirmations'
  }


  devise_scope :customer do
    get "/change-password" => "customers/registrations#edit"
    post "/change-password" => "customers/registrations#update"
    patch '/customer/confirmation' => 'customers/confirmations#update', as: :update_customer_confirmation
  end
  get 'home' => 'web_page#home'
  get 'contact-us' => 'web_page#contact_us'
  get 'about-us' => 'web_page#about_us'
  get 'fleet' => 'web_page#fleet'
  get 'services' => 'web_page#services'
  get 'vehicule-details/:id' => 'web_page#vehicule_details', as: :vehicule_details
  get 'profile-settings' => 'web_page#profile_settings', as: :profile_settings
  get 'edit-profile-settings' => 'web_page#edit_profile_settings', as: :edit_profile_settings
  patch 'profile-settings' => 'web_page#update_profile_settings'
  get 'unpaid-customer-invoices' =>'web_page#show_unpaid_customer_invoices', as: :show_unpaid_customer_invoices
  get 'unpaid-customer-invoice/:id' =>'web_page#show_unpaid_customer_invoice', as: :show_unpaid_customer_invoice
  patch 'submit-accepted-invoice' =>'web_page#submit_accepted_invoice', as: :submit_accepted_invoice
  get 'quote-request' => 'web_page#quote_request'
  get 'quote-success' => 'web_page#quote_success_page', as: :quote_success_page
  post 'quote-request' => 'web_page#create_quote_request', as: :create_quote_request
  post 'contact-us' => 'web_page#create_contact_us_quote_request', as: :create_contact_us_quote_request
  get 'history' => 'web_page#history'
  get 'jobs' => 'web_page#jobs'
  get 'jobs/apply' => 'web_page#apply_job'
  post 'jobs/apply' => 'web_page#create_job_application', as: :create_job_application
  root 'web_page#home'
end

app/controllers/web_page_controller.rb
class WebPageController < ApplicationController
  # GET home
  def home
    @current_menu_item = "home"
    @contact_us_quote = ContactUsQuote.new
  end

  def contact_us
    @current_menu_item = "contact_us"
    @contact_us_quote = ContactUsQuote.new
  end

  def about_us
    @current_menu_item = "about_us"
  end

  def quote_request
    @current_menu_item = "request_quote"
    @all_vehicules = Vehicule.all
    @airport_pickup_quote = AirportPickupQuote.new
    @airport_dropoff_quote = AirportDropoffQuote.new
    @out_of_town_quote = OutOfTownQuote.new
    @special_event_quote = SpecialEventQuote.new
    @contract_quote = ContractQuote.new
  end

  def create_contact_us_quote_request
    @contact_us_quote = ContactUsQuote.new(quote_request_params)
    if verify_recaptcha(model: @contact_us_quote) && @contact_us_quote.save
      redirect_to quote_success_page_path, notice: "Message was successfully sent. You will be receiving an email confirmation shortly at this email: #{@contact_us_quote.email}"       
    else
      render :contact_us 
    end
  end

  def create_quote_request
    captcha_verified = verify_recaptcha(model: @quote, env: ENV["RAILS_ENV"] )
    if quote_request_params[:type] == "AirportPickupQuote"
      @quote = @airport_pickup_quote = AirportPickupQuote.new(quote_request_params)
      save_result = @airport_pickup_quote.save if captcha_verified
    elsif quote_request_params[:type] == "AirportDropoffQuote"
      @quote = @airport_dropoff_quote = AirportDropoffQuote.new(quote_request_params)
      save_result = @airport_dropoff_quote.save if captcha_verified
    elsif quote_request_params[:type] == "OutOfTownQuote"
      @quote = @out_of_town_quote = OutOfTownQuote.new(quote_request_params)
      save_result = @out_of_town_quote.save if captcha_verified
    elsif quote_request_params[:type] == "SpecialEventQuote"
      @quote = @special_event_quote = SpecialEventQuote.new(quote_request_params)
      save_result = @special_event_quote.save if captcha_verified
    else
      @quote = @contract_quote = ContractQuote.new(quote_request_params)
      save_result = @contract_quote.save if captcha_verified
    end

    if captcha_verified and save_result
      redirect_to quote_success_page_path, notice: "Quote was successfully created. You will be receiving an email confirmation shortly at this email: #{@quote.email}" 
    else
      @current_menu_item = "request_quote"
      @all_vehicules = Vehicule.all
      @airport_pickup_quote = AirportPickupQuote.new unless @airport_pickup_quote
      @airport_dropoff_quote = AirportDropoffQuote.new unless @airport_dropoff_quote
      @out_of_town_quote = OutOfTownQuote.new unless @out_of_town_quote
      @contract_quote = ContractQuote.new unless @contract_quote
      @special_event_quote = SpecialEventQuote.new unless @special_event_quote
      render :quote_request 
    end
  end

  def quote_success_page 

  end

  def fleet
    @current_menu_item = "fleet"
    @type = params[:vehicule_type]
    if Vehicule.vehicule_types.keys.include?(@type)
      @vehicules = Vehicule.where(vehicule_type: @type)
    else
      @vehicules = Vehicule.all
    end
  end

  def services
    @current_menu_item = "services"
  end

  def profile_settings
    @current_menu_item = "profile"
    if current_customer.nil?
      raise ActionController::RoutingError.new('Not Found')
    else
      @current_customer = current_customer
    end
  end

  def update_profile_settings
    if current_customer.nil?
      raise ActionController::RoutingError.new('Not Found')
    end
    if current_customer.update(customer_params)
      redirect_to profile_settings_path, notice: 'Profile settings were successfully updated.' 
    else
      render "web_page/edit_profile_settings" 
    end
  end

  def edit_profile_settings
    @current_menu_item = "profile"
    if current_customer.nil?
      raise ActionController::RoutingError.new('Not Found')
    else
      @current_customer = current_customer
    end
  end

  def show_unpaid_customer_invoices
    return unless current_customer
    @current_customer = current_customer
    @invoices = current_customer.invoices.where(payed: false).to_a
    #@invoices_ready_to_pay = current_customer.invoices.where(accepted: nil, payed: nil)
  end

  def show_unpaid_customer_invoice
    return unless current_customer
    invoice_id = params[:id]
    @current_customer = current_customer
    @invoice = current_customer.invoices.where(payed: false, id: invoice_id).first
    if @invoice.blank?
      redirect_to show_unpaid_customer_invoices_path(), notice: 'Could not access invoice.'
    end
  end

  def submit_accepted_invoice
    @invoice = Invoice.find(invoice_params[:id])
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to show_unpaid_customer_invoice_path(@invoice), notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { redirect_to show_unpaid_customer_invoice_path(@invoice) }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  def vehicule_details
    @current_menu_item = "fleet"
    @vehicule = Vehicule.find(params[:id])
    @other_vehicules = Vehicule.where(vehicule_type: @vehicule.vehicule_type) - [@vehicule]
  end

  def history
    @current_menu_item = "history"
    if current_customer.nil?
      raise ActionController::RoutingError.new('Not Found')
    else
      @current_customer = current_customer
    end
  end

  def jobs
    @current_menu_item = "jobs"
  end

  def apply_job
    @current_menu_item = "jobs"
    @applicant = Applicant.new
  end

  def create_job_application
    @current_menu_item = "jobs"
    @applicant = Applicant.new(applicant_params)
    if verify_recaptcha(model: @applicant, env: ENV["RAILS_ENV"]) && @applicant.save
      redirect_to jobs_path, notice: "Application was successfully submitted."
    else
      render :apply_job
    end
  end

  private
    def applicant_params
      params.require(:applicant).permit(:first_name, :last_name, :email, :phone, :position, :note, :resume)
    end

    def invoice_params
      params.require(:invoice).permit(:id, :accepted)
    end
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :email, :phone_number)
    end

    def quote_request_params
      if params[:airport_pickup_quote]
        result = params.require(:airport_pickup_quote)
      elsif params[:airport_dropoff_quote]
        result = params.require(:airport_dropoff_quote)
      elsif params[:out_of_town_quote]
        result = params.require(:out_of_town_quote)    
      elsif params[:contract_quote]
        result = params.require(:contract_quote)
      elsif params[:special_event_quote]
        result = params.require(:special_event_quote)
      else
        result = params.require(:contact_us_quote)
      end
      result.permit(:first_name, :last_name, :email, :phone_number, :service_type, :type, :customer_id, 
            :organization, :address, :extension, :departure_date, :departure_time, :departure_address, 
            :destination_address, :vehicule_type, :itinirary, :additional_notes, :total_num_of_days, :return_date, 
            :return_time, :num_of_passengers, :num_of_bags, :airport, :flight_num, :pay_method, :flight_departure_time)
    end
end

app/views/web_page/fleet.html.erb
<!--Page Header-->
<section class="page-header listing_page">
  <div class="container">
    <div class="page-header_wrap">
      <div class="page-heading">
        <h1>Our Fleet</h1>
      </div>
      <ul class="coustom-breadcrumb">
        <li><a href="#">Home</a></li>
        <li>Our Fleet</li>
      </ul>
    </div>
  </div>
  <!-- Dark Overlay-->
  <div class="dark-overlay" style="background: rgba(0, 0, 0, 0.65) none repeat scroll 0 0;"></div>
</section>
<!-- /Page Header--> 
  
    
<!--Listing-->
<section class="listing-page">
  <div class="container">
    <div class="row">
      <div class="col-md-9 col-md-push-3">
        <% @vehicules.each do |vehicule| %>        
          <div class="product-listing-m gray-bg">
            <div class="product-listing-img"> 
              <a href="<%= vehicule.display_image_url() %>" data-lightbox=<%= "example-set-#{vehicule.id}" %> data-title="Click the right half of the image to move forward."><%= image_tag( vehicule.display_image_url(), class: "img-responsive" ) if vehicule.display_image? %> 
              </a>
              <% vehicule.vehicule_images.each do |vec_im| %>
                <%= link_to "", vec_im.photo_url(), class: "img-responsive", :data => { :lightbox => "example-set-#{vehicule.id}", :title => "Or press the right arrow on your keyboard." } %>
              <% end %>
            </div>
            <div class="product-listing-content">
              <h6><a href=<%= vehicule_details_path(vehicule.id) %> ><%= vehicule.name %></a></h6>
              <ul>
                <% if vehicule.amenities.include?("tv") %>
              <li> <i class="fa fa-television" aria-hidden="true"></i>
                flat screen tv
              </li>
            <% end %>
            <% if vehicule.amenities.include?("bathroom") %>
              <li> <i class="fa fa-bath" aria-hidden="true"></i>
                Bathroom
              </li>
            <% end %>
            <% if vehicule.amenities.include?("dvd_player") %>
              <li> <i class="fa fa-circle" aria-hidden="true"></i>
                Dvd Player
              </li>
            <% end %>
            <% if vehicule.amenities.include?("am_fm_radio") %>
              <li> <i class="fa fa-microphone" aria-hidden="true"></i>
                AM/FM Radio
              </li>
            <% end %>
            <% if vehicule.amenities.include?("cooler") %>
              <li> <i class="fa fa-snowflake-o" aria-hidden="true"></i>
                cooler
              </li>
            <% end %>
            <% if vehicule.amenities.include?("nav_system") %>
              <li> <i class="fa fa-location-arrow" aria-hidden="true"></i>
                navigation
              </li>
            <% end %>
            <% if vehicule.amenities.include?("sound_system") %>
              <li> <i class="fa fa-music" aria-hidden="true"></i>
              sound system
              </li>
            <% end %>
            <% if vehicule.amenities.include?("wheelchair") %>
              <li> <i class="fa fa-wheelchair" aria-hidden="true"></i>
                wheelchair
              </li>
            <% end %>
            <% if vehicule.amenities.include?("bluetooth") %>
              <li> <i class="fa fa-bluetooth" aria-hidden="true"></i>
                bluetooth
              </li>
            <% end %>
            <% if vehicule.amenities.include?("cd_player") %>
              <li> <i class="fa fa-circle-o" aria-hidden="true"></i>
                Cd Player
              </li>
            <% end %>
            <% if vehicule.amenities.include?("seats") %>
              <li> <i class="fa fa-user" aria-hidden="true"></i>
                <%= vehicule.seats %> seats
              </li>
            <% end %>
              </ul>
              <a href=<%= vehicule_details_path(vehicule.id) %> class="btn">View Details <span class="angle_arrow"><i class="fa fa-angle-right" aria-hidden="true"></i></span></a>
              <a href=<%= quote_request_path + "#5b" %> class="btn btn-quote">Get a quote</a>
            </div>
          </div>
        <% end %>
       
      </div>
      
      <!--Side-Bar-->
      <aside class="col-md-3 col-md-pull-9">
        <div class="sidebar_widget">
          <div class="widget_heading">  
            <h6><i class="fa fa-filter" aria-hidden="true"></i> Filter By Categories </h6>
          </div>
          <div class="sidebar_filter">
          <div class="form-group ">
            <%= link_to("All", fleet_path , class: "btn btn-primary") %>
          </div>
          <div class="form-group">
            <%= link_to("Sedans", fleet_path(vehicule_type: "sedan"), class: "btn btn-primary") %>
          </div>
          <div class="form-group">
            <%= link_to("Limousines", fleet_path(vehicule_type: "limousine"), class: "btn btn-primary") %>
          </div>
          <div class="form-group">
            <%= link_to("Shuttles", fleet_path(vehicule_type: "shuttle"), class: "btn btn-primary") %>
          </div>
          <div class="form-group">
            <%= link_to("Buses", fleet_path(vehicule_type: "bus"), class: "btn btn-primary") %>
          </div>

          </div>
        </div>
      
      </aside>
      <!--/Side-Bar--> 
    </div>
  </div>
</section>
<!-- /Listing--> 

app/views/web_page/home.html.erb
<!--Banner-->
<section id="banner2">
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
     <!-- Wrapper for slides -->
     <div class="carousel-inner">
          <!--item-1-->
       
       <div class="item active">
            <img src="assets/images/BannerNew.jpg" alt="image">
            <div class="carousel-caption">
              <div class="banner_text text-center div_zindex white-text">
                 
              </div>
            </div>
        </div>
        <!--item-2-->
        <div class="item">
            <img src="assets/images/newhome-slider2.jpg" alt="image">
            <div class="carousel-caption">
              <div class="banner_text text-center div_zindex white-text">
                  <h1>Corporate Services and VIP</h1>
                  <a href="#" class="btn">Read More</a>
              </div>
            </div>
        </div>
        <div class="item">
            <img src="assets/images/newhome_slider_downtown_night.jpg" alt="image">
            <div class="carousel-caption">
              <div class="banner_text text-center div_zindex white-text">
                  <h1>Night Out and Special Event. </h1>
                  <a href="#" class="btn">Read More</a>
              </div>
            </div>
        </div>
        <div class="item">
            <img src="assets/images/newhome-slider4.jpg" alt="image">
            <div class="carousel-caption">
              <div class="banner_text text-center div_zindex white-text">
                  <h1>Tour Buses - College and Government .</h1>
                  <a href="#" class="btn">Read More</a>
              </div>
            </div>
        </div>
        <div class="item">
            <img src="assets/images/newhome_page_slider_aiport_columbus.jpg" alt="image">
            <div class="carousel-caption">
              <div class="banner_text text-center div_zindex white-text">
                  <h1>Airport Services</h1>
                  <a href="#" class="btn">Read More</a>
              </div>
            </div>
        </div>
        <div class="item">
            <img src="assets/images/newhome_slider_van.jpg" alt="image">
            <div class="carousel-caption">
              <div class="banner_text text-center div_zindex white-text">
                  <h1>Van Services</h1>
                  <a href="#" class="btn">Read More</a>
              </div>
            </div>
        </div>
        <div class="item">
            <img src="assets/images/newhome_slider_limo.jpg" alt="image">
            <div class="carousel-caption">
              <div class="banner_text text-center div_zindex white-text">
                  <h1>Limousine Services</h1>
                  <a href="#" class="btn">Read More</a>
              </div>
            </div>
        </div>

        <div class="item" onclick="goURL()">
            <img src="assets/images/newProfile-picture-&-Cover-photo.jpg" alt="image" >
            <div class="carousel-caption">
              <div class="banner_text text-center div_zindex white-text">
                  <h1>Earn points with every booking</h1>
                  <a href="https://urbanexpress.herokuapp.com/customers/sign_up" class="btn">Read More</a>
              </div>
            </div>
        </div>
        
     </div>

          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <div class="icon-prev"></div>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <div class="icon-next"></div>
          </a>
    </div>
</section>
<!--/Banner-->


<!-- Filter-Form -->



<!--About-us-->
<section id="about_us" class="section-padding">
  <div class="container">
      <div class="section-header text-center">
          <h2>Welcome to <span style="color:red">Urban </span><span style="color:#052381">Express </span><span>Charter</span></h2>
        </div>
        
        <div class="row">
          <div class="col-md-3 col-sm-6">
              <div class="about_info">
                    <div class="icon_box">
                        <i class="fa fa-institution" aria-hidden="true"></i>
                    </div>
                    <h5>Government Transportation</h5>
                    <p>Bus, shuttle, limousine, and sedan transportation for government staff and government contracts. </p>
                    <a href="/services#government-transportation" class="btn">More</a>
                </div>
            </div>
            
            <div class="col-md-3 col-sm-6">
              <div class="about_info" >
                    <div class="icon_box">
                        <i class="fa fa-briefcase" aria-hidden="true"></i>
                    </div>
                    <h5>Corporate Transportation</h5>
                    <p>Individual and group transportation for corporate functions and affairs by bus, shuttle, limousine, and sedan . </p>
                    <a href="/services#corporate-transportation" class="btn">More</a>
                </div>
            </div>
            
            <div class="col-md-3 col-sm-6">
              <div class="about_info">
                    <div class="icon_box">
                        <i class="fa fa-calendar" aria-hidden="true"></i>
                    </div>
                    <h5>Event Transportation</h5>
                    <p>Economic limousine, bus, shuttle, and trolley rentals for weddings, parties, and other important events. </p>
                    <a href="/services#event-transportation" class="btn">More</a>
                </div>
            </div>
            
            <div class="col-md-3 col-sm-6">
              <div class="about_info">
                    <div class="icon_box">
                        <i class="fa fa-wheelchair" aria-hidden="true"></i>
                    </div>
                    <h5>Handicap Accessible</h5>
                    <p>We offer vehicles that are wheelchair accessible and include amenities for the disabled. </p>
                    <a href="/services#handicap-transportation" class="btn">More</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!--/About-us-->

<!-- Fun Facts-->
<section class="fun-facts-section">
  <div class="container div_zindex">
    <h3 class="what-we-offer">WHAT WE OFFER</h3>
    <div class="row">
      <div class="col-lg-3 col-xs-6 col-sm-3">
        <div class="fun-facts-m">
          <div class="cell">
            <h2><i class="fa fa-users" aria-hidden="true"></i></h2>
            <p>Quality Customer Service</p>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-xs-6 col-sm-3">
        <div class="fun-facts-side">Urban Express Charter is proud to offer live personal assistance 24 hours a day, 7 days a week. Someone is always available to assist you with your transportation needs.</div>
      </div>
      <div class="col-lg-3 col-xs-6 col-sm-3">
        <div class="fun-facts-m">
          <div class="cell">
            <h2><i class="fa fa-car" aria-hidden="true"></i></h2>
            <p>Professionally Trained Drivers</p>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-xs-6 col-sm-3">
        <div class="fun-facts-side">All Urban Express Charter drivers have been professionally trained to provide only the most impressive transportation services. UEC drivers will ensure that you arrive at your destination promptly.</div>
      </div>
      <div class="col-lg-3 col-xs-6 col-sm-3">
        <div class="fun-facts-m">
          <div class="cell">
            <h2><i class="fa fa-road" aria-hidden="true"></i></h2>
            <p>Nationwide Transportation &nbsp; Services</p>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-xs-6 col-sm-3">
        <div class="fun-facts-side">Although Urban Express Charter is a Columbus, Ohio based company, we provide our transportation services nationwide.</div>
      </div>
      <div class="col-lg-3 col-xs-6 col-sm-3">
        <div class="fun-facts-m">
          <div class="cell">
            <h2><i class="fa fa-percent" aria-hidden="true"></i></h2>
            <p>Minimal Deposit Requirement</p>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-xs-6 col-sm-3">
        <div class="fun-facts-side">To reserve our limousine, bus, shuttle, trolley, or sedan car rental services Urban Express Charter only requires a small 20% non-refundable deposit.</div>
      </div>  
    </div>
  </div>
  <!-- Dark Overlay-->
  <div class="dark-overlay"></div>
</section>
<!-- /Fun Facts--> 


<!-- Services -->
<section id="our_services" class="dark-bg vc_row page-header">
  <div class=" col-md-6 vc_col section-padding">
      <div class="our_services white-text">
          <h2>Announcing our new Rewards Program!</h2>
          <p>Urban Express is happy to announce our new Rewards program for our valued customers. <%= link_to "Register",new_customer_registration_path %> with us and <%= link_to "Login", new_customer_session_path %> to access your reward points.</p>
          <div class="services_info">
              <div class="icon_box">
                  <i class="fa fa-money" aria-hidden="true"></i>
              </div>
              <h4>Earn points with every booking</h4>
              <p>With each booking, reward points will be added to your account.</p>
          </div>
          
          <div class="services_info">
              <div class="icon_box">
                  <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
              </div>
              <h4>Use earned points towards future bookings</h4>
              <p>You can redeem points by applying them towards a booking request.</p>
          </div>
      </div>
  </div>
  <div class=" col-md-4 section-padding">
      <div class="contact_form white-text">
        <h2>Contact Us</h2>
        <%= simple_form_for(@contact_us_quote, url: create_contact_us_quote_request_path(), method: :post) do |f| %>
          <%= f.error_notification %>
          <%= f.input :type, as: :hidden %>
          <div class="form-group" style="float:left;width:50%;padding-right:10px;">
            <%= f.input :first_name, required: true, input_html: {class: "form-control white_bg"} %>
          </div>
          <div class="form-group" style="float:left;width:50%;padding-left:10px;">
            <%= f.input :last_name, required: true, input_html: {class: "form-control white_bg"} %>
          </div>
          <div class="form-group" style="float:left;width:50%;padding-right:10px;">
            <%= f.input :email, required: true, input_html: {class: "form-control white_bg"} %>
          </div>
          <div class="form-group" style="float:left;width:50%;padding-left:10px;">
            <%= f.input :phone_number, input_html: {class: "form-control white_bg"} %>
          </div>
          <div class="form-group" style="clear:both;">
            <%= f.input :additional_notes, as: :text, input_html: {class: "white_bg", :cols => 40, :rows => 8 } %>
          </div>
          <div class="row">
            <div class="form-group col-md-8">
              <%= recaptcha_tags %>
            </div>
            <div class="form-group col-md-6">
              <%= f.button :submit, "Send Message"%>
            </div>
          </div>
        <% end %>
      </div>
  </div>
  <div class="dark-overlay" style="background: rgba(0, 0, 0, 0.3) none repeat scroll 0 0;"></div>
</section>
<!-- /Services -->


<!--Testimonial 
<section id="testimonial" class="section-padding">
  <div class="container div_zindex">
    <div class="section-header text-center">
      <h2>Our Testimonial</h2>
      <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. </p>
    </div>
    <div class="row">
      <div id="testimonial-slider-2">
           <div class="testimonial_wrap">
               <div class="testimonial-heading">
                  <h5>JOHN KEIPPER</h5>
                  <span class="client-designation">Client</span> 
               </div>
               <p>I used Urban Express to take a group down to the Kentucky Derby. Our driver was very professional and delivered us right to the main entrance. I would definitely use them again in the future. The service was great!</p>
           </div>
           
           <div class="testimonial_wrap">
               <div class="testimonial-heading">
                  <h5>JAMAL SALIH </h5>
                  <span class="client-designation">Client</span> 
               </div>
               <p>Great experience with this company I have used many others in columbus but this was by far the best you guys made our trip so easy. Great customer service, wonderful drivers and by far the best and most affordable transportation company I have used in central ohio. Thank you soo much!</p>
           </div>
           
           <div class="testimonial_wrap">

               <div class="testimonial-heading">
                  <h5> LISA SEVOSA</h5>
                  <span class="client-designation">Client</span> 
               </div>
               <p>I hired Urban Express to pick me up at the airport with their Mercedes. I had just got back from a long trip in Germany and was very tired. The driver was on time and extremely courteous and I had no problems at all. I wanted to write a review and share my experience because it was not a good with other Columbus transportation companies.</p>
           </div>
        
      </div>
    </div>
  </div>

</section>
 Testimonial--> 

app/views/web_page/quote_success_page.html.erb
Thank you!!